---
# Copyright 2017, Rackspace US, Inc.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in witing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

- name: Gather facts
  hosts: vm_hosts
  gather_facts: "{{ gather_facts | default(true) }}"
  pre_tasks:
    - name: Gather variables for each operating system
      include_vars: "{{ item }}"
      with_first_found:
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}-{{ ansible_distribution_major_version | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_distribution | lower }}.yml"
        - "{{ playbook_dir }}/vars/{{ ansible_os_family | lower }}.yml"
      tags:
        - always

  tasks:
    - name: Create VM LV
      lvol:
        vg: vg01
        lv: "{{ item.server_hostname }}"
        size: "{{ default_vm_storage }}"
      with_items: "{{ servers }}"

    - name: Create the VM template
      template:
        src: kvm/kvm-vm.xml
        dest: "/etc/libvirt/qemu/{{ item.server_hostname }}.xml"
        mode: 0644
        owner: root
        group: root
      with_items: "{{ servers }}"

    - name: Define the VM
      command: "virsh define /etc/libvirt/qemu/{{ item.server_hostname }}.xml"
      failed_when: false
      with_items: "{{ servers }}"

    - name: Create the VM
      command: "virsh create /etc/libvirt/qemu/{{ item.server_hostname }}.xml"
      failed_when: false
      with_items: "{{ servers }}"

    - name: Start the VM
      command: "virsh start {{ item.server_hostname }}"
      failed_when: false
      with_items: "{{ servers }}"

  vars_files:
    - vars/main.yml
  tags:
    - setup-host
